Fix fetch_markers passing list instead of dict (#451)
* Update user.py

The Twitch API describes the "videos" element in the response as "A list of videos that contain markers. The list contains a single video." Currently, that list is being passed when creating the VideoMarkers object, when only the first element of that "list" should be.

This fixes this issue that arises when retrieving markers:
```  File "C:\Users\Zari\AppData\Roaming\Python\Python312\site-packages\twitchio\models.py", line 814, in __init__
    self.markers = [Marker(d) for d in data["markers"]]
                                       ~~~~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str```

* Update changelog.rst

* Update changelog.rst

---------

Co-authored-by: Tom <iamtomahawkx@gmail.com>